name: primary_bid
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

# TODO: Alphabetise

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.1
  either_dart: ^0.1.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  http: ^0.13.4
  path_provider: ^2.0.11
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true
  fonts:
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-Medium.ttf
        - asset: assets/fonts/Mukta-Bold.ttf
          weight: 700